version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Frontend Build
          command: npm run build
      - aws-cli/install
      - run:
          name: Frontend Deployment
          command: npm run deploy
  server:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Server Build and Archive
          command: npm run build
      - aws-cli/install
      - eb/setup
      - run:
          name: Server Deployment
          command: npm run deploy
workflows:
  build_and_deploy:
    jobs:
      - server:
          filters:
            branches:
              only: 
                - master
      - frontend:
          filters:
            branches:
              only: 
              - master
          