version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
jobs:
  frontend-build:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Frontend Build
          command: npm run fe:build
  frontend-deploy:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - aws-cli/install
      - run:
          name: Frontend Deployment
          command: npm run fe:deploy
  server-build:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Server Build and Archive
          command: npm run api:build
  server-deploy:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - aws-cli/install
      - run:
          name: Server Deployment
          command: npm run api:deploy
workflows:
  build_and_deploy:
    jobs:
      - server-build
          filters:
            branches:
              only: master
      - server-deploy
          requires: 
            - server-build
            filters:
              branches:
                only: master
      - frontend-build
        filters:
          branches:
            only: master
      - frontend-deploy
          requires:
              - frontend-build
            filters:
              branches:
                only: master
          