version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
jobs:
  frontend-build:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Frontend Build
          command: npm run build
  frontend-deploy:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - aws-cli/install:
          profile-name: default
      - run:
          name: Frontend Deployment
          command: npm run deploy
  server-build:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Server Build and Archive
          command: npm run build
  server-deploy:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - aws-cli/install:
          profile-name: default
      - run:
          name: Install Elastic Beanstalk
          command: |
            - sudo apt-get -y -qq update
            - sudo apt-get install python3-pip python3-dev build-essential
            - sudo pip3 install awsebcli
      - run:
          name: Server Deployment
          command: eb deploy udagram-api-env
workflows:
  build_and_deploy:
    jobs:
      - server-build:
          filters:
            branches:
              only: 
                - master
      - server-deploy:
          requires:
            - server-build
          filters:
            branches:
              only:
                - master
      - frontend-build:
          filters:
            branches:
              only: 
              - master
      - frontend-deploy:
          requires:
              - frontend-build
          filters:
            branches:
              only: 
                - master
          