version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
jobs:
  frontend-build:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Frontend Build
          command: npm run build
  frontend-deploy:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - aws-cli/install
      - run:
          name: Frontend Deployment
          command: aws s3 cp D:\COURSES\Programming\WEB\Advanced Web Development\3. Deployment Process\project\udagram-frontend\www s3://udagram-mohamed
  server-build:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Server Build and Archive
          command: npm run build
  server-deploy:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - aws-cli/install
      - run:
          name: Server Deployment
          command: |-
            aws s3 cp ./www/Archive.zip $S3_BUCKET_SERVER
            aws elasticbeanstalk create-application-version --application-name udagram-app --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$AWS_BUCKET",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name udagram-app --environment-name udagram-app-env --version-label <<pipeline.git.revision>>
workflows:
  build_and_deploy:
    jobs:
      - server-build:
          filters:
            branches:
              only: 
                - master
      - server-deploy:
          requires:
            - server-build
          filters:
            branches:
              only:
                - master
      - frontend-build:
          filters:
            branches:
              only: 
              - master
      - frontend-deploy:
          requires:
              - frontend-build
          filters:
            branches:
              only: 
                - master
          