version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend-build:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Frontend Build
          command: npm run build
  frontend-deploy:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - aws-cli/install
      - run:
          name: Frontend Deployment
          command: aws s3 cp --recursive --acl public-read ./www s3://udagram-mohamed/
  server-build:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Server Build and Archive
          command: npm run build
  server-deploy:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - aws-elastic-beanstalk/install
      - run:
          name: Server Deployment
          command: npm run deploy
workflows:
  build_and_deploy:
    jobs:
      - server-build:
          filters:
            branches:
              only: 
                - master
      - server-deploy:
          requires:
            - server-build
          filters:
            branches:
              only:
                - master
      - frontend-build:
          filters:
            branches:
              only: 
              - master
      - frontend-deploy:
          requires:
              - frontend-build
          filters:
            branches:
              only: 
                - master
          